# reference: https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017 # https://www.appveyor.com/docs/windows-images-software/

version: "#{build} ({branch})"

#region JAVA
environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk12

install:
  - SET PATH=%JAVA_HOME%\bin;%PATH
  - java --version
#endregion

#region GRADLE
build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check

cache:
  - C:\Users\appveyor\.gradle
#endregion
